# Generated by Django 2.2.4 on 2019-08-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_auto_20190817_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='executor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
